# Generated by Django 5.1 on 2026-07-26 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('record_type', models.CharField(choices=[('doctor_note', 'Doctor Note'), ('nursing_note', 'Nursing Note'), ('lab_report', 'Lab Report'), ('radiology_report', 'Radiology Report'), ('pharmacy_record', 'Pharmacy Record'), ('blood_bank_record', 'Blood Bank Record'), ('admission_record', 'Admission Record'), ('ot_record', 'Operation Theatre Record'), ('insurance_doc', 'Insurance Document'), ('uploaded_pdf', 'Uploaded PDF'), ('uploaded_scan', 'Uploaded Scan'), ('note', 'Note')], default='note', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='medical_records/')),
                ('uploaded_by', models.CharField(blank=True, max_length=200)),
                ('staff_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
