# Generated by Django 5.1 on 2026-07-26 03:21

import admissions.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=20)),
                ('is_occupied', models.BooleanField(default=False)),
                ('bed_type', models.CharField(choices=[('general', 'General'), ('semi_private', 'Semi-Private'), ('private', 'Private'), ('icu', 'ICU'), ('nicu', 'NICU')], default='general', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_id', models.CharField(default=admissions.models.generate_admission_id, editable=False, max_length=20, unique=True)),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('treatment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('admitted', 'Admitted'), ('discharged', 'Discharged')], default='admitted', max_length=20)),
                ('admission_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('barcode', models.ImageField(blank=True, upload_to='barcodes/admissions/')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='patients.patient')),
                ('bed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.bed')),
            ],
        ),
        migrations.CreateModel(
            name='DischargeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_diagnosis', models.TextField(blank=True)),
                ('final_diagnosis', models.TextField(blank=True)),
                ('chief_complaint', models.TextField(blank=True)),
                ('history_of_present_illness', models.TextField(blank=True)),
                ('examination_findings', models.TextField(blank=True)),
                ('investigations', models.TextField(blank=True, help_text='Lab/Radiology findings summary')),
                ('treatment_given', models.TextField(blank=True)),
                ('condition_at_discharge', models.CharField(choices=[('improved', 'Improved'), ('stable', 'Stable'), ('unchanged', 'Unchanged'), ('deteriorated', 'Deteriorated')], default='improved', max_length=50)),
                ('discharge_instructions', models.TextField(blank=True, help_text='Instructions for patient after discharge')),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_instructions', models.TextField(blank=True)),
                ('medications_at_discharge', models.TextField(blank=True, help_text='List of medications prescribed at discharge')),
                ('prepared_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by_doctor', models.BooleanField(default=False)),
                ('barcode', models.ImageField(blank=True, upload_to='barcodes/discharge/')),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_summary', to='admissions.admission')),
                ('attending_doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('floor', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.department')),
            ],
        ),
        migrations.AddField(
            model_name='bed',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.ward'),
        ),
        migrations.AddField(
            model_name='admission',
            name='ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.ward'),
        ),
    ]
