# Generated by Django 5.1 on 2026-07-26 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('instructions', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(blank=True)),
                ('clinical_notes', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctor')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.opdvisit')),
                ('prescriptions', models.ManyToManyField(blank=True, to='consultations.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='LabTestRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('clinical_note', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='routine', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('sample_collected', 'Sample Collected'), ('testing', 'Testing'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('result_notes', models.TextField(blank=True)),
                ('result_file', models.FileField(blank=True, upload_to='lab_results/')),
                ('referral_file', models.FileField(blank=True, upload_to='lab_referrals/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('barcode', models.ImageField(blank=True, upload_to='barcodes/lab/')),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultations.consultation')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='RadiologyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imaging_type', models.CharField(choices=[('xray', 'X-Ray'), ('ct', 'CT'), ('mri', 'MRI'), ('ecg', 'ECG'), ('echo', 'Echo'), ('ultrasound', 'Ultrasound'), ('custom', 'Custom')], max_length=50)),
                ('custom_type', models.CharField(blank=True, max_length=200)),
                ('clinical_note', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='routine', max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='requested', max_length=20)),
                ('findings', models.TextField(blank=True)),
                ('impression', models.TextField(blank=True)),
                ('result_notes', models.TextField(blank=True)),
                ('result_file', models.FileField(blank=True, upload_to='radiology_results/')),
                ('referral_file', models.FileField(blank=True, upload_to='radiology_referrals/')),
                ('request_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('barcode', models.ImageField(blank=True, upload_to='barcodes/radiology/')),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultations.consultation')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
