# Generated by Django 5.1 on 2026-07-26 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NursingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('nursing_note', 'Nursing Note'), ('vital_signs', 'Vital Signs'), ('progress', 'Progress Note'), ('observation', 'Observation'), ('medication_admin', 'Medication Administration')], default='nursing_note', max_length=50)),
                ('content', models.TextField()),
                ('vital_bp', models.CharField(blank=True, max_length=50)),
                ('vital_temp', models.CharField(blank=True, max_length=50)),
                ('vital_pulse', models.CharField(blank=True, max_length=50)),
                ('vital_resp', models.CharField(blank=True, max_length=50)),
                ('attached_file', models.FileField(blank=True, upload_to='nursing_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
