# Generated by Django 5.1 on 2026-07-26 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RadiologyCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('imaging_type', models.CharField(choices=[('xray', 'X-Ray'), ('ct', 'CT'), ('mri', 'MRI'), ('ecg', 'ECG'), ('echo', 'Echo'), ('ultrasound', 'Ultrasound')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
