# Generated by Django 5.1 on 2026-07-26 03:21

import django.db.models.deletion
import patients.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('departments', '0001_initial'),
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(default=patients.models.generate_patient_id, editable=False, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(editable=False, max_length=200)),
                ('age_value', models.IntegerField(default=0, help_text='Age numeric value')),
                ('age_type', models.CharField(choices=[('years', 'Years'), ('months', 'Months'), ('weeks', 'Weeks'), ('days', 'Days')], default='years', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, help_text='Optional — if provided, age is auto-calculated', null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('phone', models.CharField(help_text='Primary phone number', max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address_line', models.TextField(blank=True)),
                ('municipality', models.CharField(blank=True, help_text='Municipality/Rural Municipality', max_length=200)),
                ('ward_number', models.CharField(blank=True, help_text='Ward Number', max_length=20)),
                ('tole', models.CharField(blank=True, help_text='Tole/Street name', max_length=200)),
                ('emergency_contact_name', models.CharField(blank=True, help_text='Emergency contact person name', max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, help_text='Emergency contact phone', max_length=20)),
                ('emergency_contact_relation', models.CharField(blank=True, help_text='Relation to patient', max_length=100)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10)),
                ('allergies', models.TextField(blank=True)),
                ('chronic_conditions', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='patients/')),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('registration_source', models.CharField(choices=[('counter', 'Registration Counter'), ('online', 'Online Portal')], default='counter', max_length=20)),
                ('is_new_patient', models.BooleanField(default=True, help_text='New vs returning patient for fee calculation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.district')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.province')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OPDVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_number', models.IntegerField(default=1)),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='waiting', max_length=20)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('esewa', 'eSewa')], default='cash', max_length=20)),
                ('visit_type', models.CharField(choices=[('new', 'New Patient'), ('follow_up', 'Follow-up')], default='new', max_length=20)),
                ('clinical_notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.department')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opd_visits', to='patients.patient')),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
    ]
